version: '3.4'

services:
  identity:
    image: identity-udv
    ports:
      - "5215:5215"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=123;Host=db;Port=5432;Database=identityNEOLab;Pooling=true;
    networks:
      - database

  tests:
    image: tests-udv
    ports:
      - "5068:5068"
    depends_on:
      - tests-db
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=123;Host=tests-db;Port=5432;Database=testsNEOLab;Pooling=true;
    networks:
      - database
    
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: identityNEOLab
    networks:
      - database

  tests-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: testsNEOLab
    networks:
      - database

volumes:
  postgres_data:

networks:
  database:
    driver: bridge